export interface Car {
  id: number;
  name: string;
  picture: string;
  gear: string;
  type: string;
  capacity: number;
  price: number;
  litres: number;
  liked: boolean;
}
export const cars: Car[] = [
  {
    id: 1,
    name: "Select Car",
    picture: "/logo.png",
    gear: "N/A",
    type: "N/A",
    capacity: 0,
    price: 0,
    litres: 0,
    liked: false,
  },
  {
    id: 2,
    name: "Rolls roys",
    picture: "/rolls.png",
    gear: "automatic",
    type: "luxury saloon",
    capacity: 6,
    price: 490,
    litres: 70,
    liked: false,
  },
  {
    id: 3,

    name: "Duster",
    picture: "/duster.png",
    gear: "manual",
    type: "SUV",
    capacity: 6,
    price: 50,
    litres: 70,
    liked: true,
  },
  {
    id: 4,

    name: "Mercedes AMG",
    picture: "/amg.png",
    gear: "manual",
    type: "Sport",
    capacity: 4,
    price: 90,
    litres: 90,
    liked: false,
  },
  {
    id: 5,

    name: "Bently Continental",
    picture: "/bently.png",
    gear: "Automatic",
    type: "Luxury Car",
    capacity: 6,
    price: 350,
    litres: 70,
    liked: false,
  },
  {
    id: 9,
    name: "Ford Mustang",
    picture: "/mustang.png",
    gear: "Automatic",
    type: "Sport",
    capacity: 2,
    price: 80,
    litres: 40,
    liked: false,
  },
  {
    id: 6,
    name: "Bugatti",
    picture: "/bugatti.png",
    gear: "Automatic",
    type: "Luxury Car",
    capacity: 2,
    price: 750,
    litres: 80,
    liked: false,
  },
  {
    id: 7,
    name: "Chevy Camaro",
    picture: "/camaro.png",
    gear: "Automatic",
    type: "Sport",
    capacity: 4,
    price: 80,
    litres: 50,
    liked: false,
  },
  {
    id: 8,
    name: "Ferrari",
    picture: "/ferrari.png",
    gear: "Automatic",
    type: "Sport",
    capacity: 2,
    price: 150,
    litres: 60,
    liked: false,
  },
];

/*{
  id: 10,
  name: "Audi A4",
  picture: "/a4.png",
  gear: "Automatic",
  type: "Sedan",
  capacity: 5,
  price: 70,
  litres: 60,
  liked: false,
},
{
  id: 11,
  name: "Toyota Prius",
  picture: "/prius.png",
  gear: "Automatic",
  type: "Hybrid",
  capacity: 5,
  price: 60,
  litres: 50,
  liked: false,
},
{
  id: 12,
  name: "Nissan GT-R",
  picture: "/gtr.png",
  gear: "Automatic",
  type: "Sports Car",
  capacity: 2,
  price: 180,
  litres: 70,
  liked: false,
},
{
  id: 13,
  name: "Volvo XC90",
  picture: "/xc90.png",
  gear: "Automatic",
  type: "SUV",
  capacity: 7,
  price: 85,
  litres: 75,
  liked: false,
},
{
  id: 14,
  name: "BMW X5",
  picture: "/x5.png",
  gear: "Automatic",
  type: "SUV",
  capacity: 5,
  price: 100,
  litres: 80,
  liked: false,
},
{
  id: 15,
  name: "Hyundai Tucson",
  picture: "/tucson.png",
  gear: "Automatic",
  type: "SUV",
  capacity: 5,
  price: 40,
  litres: 60,
  liked: false,
},
{
  id: 16,
  name: "Lamborghini Huracan",
  picture: "/huracan.png",
  gear: "Automatic",
  type: "Sports Car",
  capacity: 2,
  price: 250,
  litres: 70,
  liked: false,
},
{
  id: 17,
  name: "Porsche 911",
  picture: "/porsche.png",
  gear: "Automatic",
  type: "Sports Car",
  capacity: 2,
  price: 200,
  litres: 60,
  liked: false,
},
{
  id: 18,
  name: "Mazda MX-5",
  picture: "/mx5.png",
  gear: "Manual",
  type: "Sports Car",
  capacity: 2,
  price: 55,
  litres: 50,
  liked: false,
},
{
  id: 19,
  name: "Subaru Outback",
  picture: "/outback.png",
  gear: "Automatic",
  type: "Crossover",
  capacity: 5,
  price: 45,
  litres: 65,
  liked: false,
},
{
  id: 20,
  name: "Honda Civic",
  picture: "/civic.png",
  gear: "Automatic",
  type: "Compact",
  capacity: 5,
  price: 30,
  litres: 45,
  liked: false,
} */
